# Site
repository: AimarUrteaga/curr-culum-vitae
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Aimar Urteaga
title: Ingeniero Informático
email: aimar@aimar.es
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: aimarostia
github_username:  aimarurteaga
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: aimar_urteaga
linkedin_username: aimarurteaga
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: "@aimarurteaga"
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: |
  Soy un estudiante de ingeniería informática interesado en la programación a bajo nivel, ciberseguridad, sistemas empotrados, sistemas operativos, sistemas de computo en paralelo y administración de sistemas.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        border: weak  # Value of `weak` will display a weak border below this item. # Any 
#                      # other value (or no value) means no border will be displayed
#        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project
  - title: Experiencia profesional
    layout: list
    content:
      - layout: left
        title: Eurocibcar
        sub_title: Investigación y desarrollo.
        caption: Enero 2023 - Junio 2023
        link: https://eurocybcar.com/
        quote: >
          Es una empresa tecnológica que da servicios a otras empresas y a entidades gubernamentales. El principal servicio que ofrecen son auditorías sobre la ciberseguridad de vehículos. El objetivo es el de proteger la vidas tanto de los usuarios de estos vehículos como su información personal.
        description: | # this will include new lines to allow paragraphs
          La principal tarea relizada ha sido la investigación y desarrollo de un dron. Para este proyecto completé las estapas iniciales del desarrollo, desde las definiciones de la funcionalidad, un estudio de la viabilidad del proyecto, estado del arte, decidir los componentes que se iban a utilizar para la construcción del primer prototipo y un comienzo del desarrollo del software.
    
      - layout: left
        title: Eurocibcar
        sub_title: Apoyo en el Área Técnica en el área de programación
        caption: Octubre 2022 - Diciembre 2022
        link: https://eurocybcar.com/
        quote: >
          Es una empresa tecnológica que da servicios a otras empresas y a entidades gubernamentales. El principal servicio que ofrecen son auditorías sobre la ciberseguridad de vehículos. El objetivo es el de proteger la vidas tanto de los usuarios de estos vehículos como su información personal.
        description: | # this will include new lines to allow paragraphs
          Unas prácticas en las que las principales tareas que realicé fue: desarrollo de una aplicación web, la arquitectura de una red de intranet junto con todos los servidores que la componían y el desarrollo de un simulador que integraba una interfaz gráfica junto con un bus can.

  - title: Educación
    layout: list
    content:
      - layout: top-left
        title: Master en ingenieria de sistemas empotrados
        sub_title: Universidad del País Vasco
        caption: 2023 - 2025
        quote: >
          Master especializado en programación a bajo nivel
        description:
          Este master se basa en obtener un conocimiento profundo sobre el hardware en el que se opera llegando a realizar programación bare metal y módulos de kernel de linux. Además, también se aprende ha realizar diseños en FPGA mediante BHDL. Por último cabe destacar el conocimiento adquirido en control y en procesamiento de señales digitales.
        
      - layout: top-left
        title: Ingeniería informática
        sub_title: Universidad del País Vasco
        caption: 2019 - 2024
        quote: >
          Ingeniería informática en la especialización en ingeniería de computadores
        description:
          Esta especialidad se centra, a parte de en los básicos comunes de la informática, en la ciberseguridad, diseño de redes, computación paralela, diseño de hardware, programación de sistemas empotrados, administración de sistemas y utilización de distintos aceleradores (como puede ser tarjetas gráficas por ejemplo).
      
      - layout: top-left
        title: Bachillerato científico
        sub_title: Txorierri institutua bhi
        caption: 2017 - 2019
          
  - title: Lenguajes de programación
    layout: text
    content: | # this will include new lines to allow paragraphs
      - C: Muy elevado
      
      - Java: Muy elevado
      
      - Python: Elevado
      
      - JavaScript: Medio
      
      - PHP: Medio
      
      - SQL: Medio
      
      - Bash/Shell: Medio
      
      - HTML/CSS: Bajo
      
  - title: Idiomas
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Castellano: Nativo
      
      - Euskera: Nativo
      
      - Ingles: Medio

  - title: Certificaciones y permisos
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Carnet de conducir (B): Dispongo del carnet de conducir B junto con coche propio. Éste me habilita para operar automóviles cuya masa máxima autorizada no exceda de 3.500 kg que estén diseñados y construidos para el transporte de no más de 9 personas.
      
      - Operador drone (A1): Dispongo de la autorización para operar drones de hasta 900g en zonas pobladas con tránsito de personas.

      - Operador drone (A2): Dispongo de la autorización para operar drones de hasta 4Kg en zonas pobladas a una distancia de seguridad del tránsito de personas.

      - Operador drone (A3): Dispongo de la autorización para operar drones de hasta 25Kg a distancias minimas de 150m de cualquier persona o zona residencial, comercial, industriales y recreativa.

  - title: Un poquito más sobre mí
    layout: text
    content: | # this will include new lines to allow paragraphs
      Soy una persona que disfruta trabajando en equipo. Presento una actitud cordial y respetuosa tanto en la vida personal como en el trabajo por lo que me gusta participar en equipo y tanto recibir ayuda como ayudar a mis compañeros. Soy una persona disléxica, por lo cual leo de manera mas lenta que la media. También, disgráfico esto implica que mi letra es poco clara de entender y disortográfico por lo que cometo faltas ortográficas. Aun asi mi comprensión lectora es excelente (por encima de la media) y nunca he tenido ningún problema al respecto. Soy una persona curiosa y apasionada por la informatica y la ciencia lo que me hace esforzarme y disfrutar por aprender nuevas cosas en este ámbito.
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
