# Site
repository: AimarUrteaga/curr-culum-vitae
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Aimar Urteaga
title: Ingeniero Informatico
email: aimar@aimar.es
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: aimarostia
github_username:  aimarurteaga
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: aimar_urteaga
linkedin_username: aimarurteaga
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: "@aimarurteaga"
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: |
  Soy un estudiante de inejenieria informatica interesado en la programacion a bajo nivel, ciberseguridad, sistemas empotrados y sistemas operativos. Tambien disfruto de diseño de redes y sistemas de computo en paralelo.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        border: weak  # Value of `weak` will display a weak border below this item. # Any 
#                      # other value (or no value) means no border will be displayed
#        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project
  - title: Experiencia profesional
    layout: list
    content:
      - layout: left
        title: Eurocibcar
        sub_title: Apoyo en el Área Técnica en el área de programación
        caption: Octubre 2022 - Diciembre 2022
        link: https://eurocybcar.com/
        quote: >
          Es una empresa tecnológica que da servicios a otras empresas y a entidades gubernamentales. El principal servicio que ofrecen son auditorías sobre la civerseguridad de vehículos. Esto con el objetivo de proteger la vidas tanto de los usuarios de estos vehículos como su información personal.
        description: | # this will include new lines to allow paragraphs
          Unas practicas en las que las principales tareas que realice fue desarrolo de una aplicacion web el diesño de una red y el de un simulador con interfaz grafica.
          
      - layout: left
        title: Eurocibcar
        sub_title: Investigacón y desarrollo.
        caption: Enero 2023 - Actualidad
        link: https://eurocybcar.com/
        quote: >
          Es una empresa tecnológica que da servicios a otras empresas y a entidades gubernamentales. El principal servicio que ofrecen son auditorías sobre la civerseguridad de vehículos. Esto con el objetivo de proteger la vidas tanto de los usuarios de estos vehículos como su información personal.
        description: | # this will include new lines to allow paragraphs
          La principal tarea relizada ha sido la ivestigaccion y desarrolo de un dron.

  - title: Educación
    layout: list
    content:
      - layout: top-left
        title: Ingenieria informatica
        sub_title: Universidad del País Vasco
        caption: 2019 - 2023
        quote: >
          Ingenieria informatica en la especializado en ingeniería de computadores
        description: | # this will include new lines to allow paragraphs
          Esta especialidad se centra a parte de en los basicos comunes de la informatica en la ciberseguridad, diseño de redes, computacion paralela, diseño de hardware, programación de sistemas empotrados, administracción de sistemas y utilización de distintos aceleradores como puede der tarjetas graficas por ejemplo.
      
      - layout: top-left
        title: Bachillerato cientifico
        sub_title: Txorierri institutua bhi
        caption: 2017 - 2019
          
  - title: Lenguajes de programación
    layout: text
    content: | # this will include new lines to allow paragraphs
      - C: Muy elevado
      
      - Java: Muy elevado
      
      - Python: Elevado
      
      - JavaScript: Medio
      
      - PHP: Medio
      
      -SQL: Medio
      
      -Bash/Shell: Medio
      
      -HTML/CSS: Bajo
      
  - title: Lenguajes de programación
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Castellano: Muy elevado
      
      - Euskera: Muy elevado
      
      - Ingles: Medio
  
  - title: Un poquito mas sobre mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Soy dislexico, eso significa que leo de manera mas lenta que la media aunque la compresion lectora es adecuada y nunca he tenido problemas en ese aspecto. Tambien soy disgrafico lo cual significa que mi letra es lijeramente dificil de entender y soy disortografíco lo cual significa que cometo muchas faltas ortograficas. Soy una persona curiosa y apasionada por la informatica y la ciencia, ademas de amigable por lo tento disfruto de trabajar en equipo.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
